device_num = 2

virtual_resources = [
    "crane:current:ResourceFloat",
    "crane:voltage:ResourceFloat"
]

[[devices]]
device_id = "001"
device_name = "设备001"
device_description = "这是一个上电设备"
device_profile = "crane"

[[devices]]
device_id = "002"
device_name = "设备002"
device_description = "这是一个上电设备"
device_profile = "crane"
